name: jogr
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.19.0-5.0.pre

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  provider: ^4.1.3
  google_sign_in: ^4.5.1
  flutter_spinkit: ^4.1.2+1
  cool_nav: ^0.0.1
  fl_chart: ^0.10.0
  month_picker_dialog: ^0.3.2
  google_maps_flutter: ^0.5.28+1
  flutter_background_location: ^0.0.4 # Not needed
  background_locator: ^1.1.7+1
  latlong: ^0.6.1
  location: ^3.0.0
  flutter_polyline_points: ^0.2.2
  dio: ^3.0.9
  sliding_up_panel: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/google_logo.png
    - assets/map_theme.json

  uses-material-design: true

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CustomIcons
      fonts:
        - asset: icons/CustomIcons.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages